export interface CsCoursePortal {
  id: string;
  title: string;
  provider: "MIT OCW" | "Stanford Online" | "NPTEL / IIT" | "Harvard CS50" | "Coursera" | "Gate Smashers" | "Abdul Bari" | "FreeCodeCamp" | "CMU" | "UC Berkeley";
  instructor: string;
  url: string;
  rating: number; // e.g. 4.9
  enrolledStudents?: string;
  duration: string;
  level: "Beginner" | "Intermediate" | "Advanced" | "Comprehensive";
  description: string;
  tags: string[];
}

export interface CsSubjectItem {
  id: string;
  subject: string;
  code: string;
  category: string;
  description: string;
  targetDepth: string;
  recommendedHours: number;
  topCourses: CsCoursePortal[];
  syllabusTopics: string[];
}

export interface CsQuizMcqQuestion {
  id: string;
  question: string;
  codeSnippet?: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  difficulty: "Easy" | "Medium" | "Hard";
}

export interface CsQuizItem {
  id: string;
  quizNumber: number;
  subjectId: string;
  subjectName: string;
  title: string;
  subtopic: string;
  targetLevel: "Core Foundation" | "Advanced Mastery" | "Tier 1 Specialist";
  durationMinutes: number;
  passingScore: number;
  section1Easy: CsQuizMcqQuestion[]; // 5 Easy questions
  section2Medium: CsQuizMcqQuestion[]; // 5 Medium questions
  section3Hard: CsQuizMcqQuestion[]; // 5 Hard questions
}

// ─────────────────────────────────────────────────────────────────────────────
// 1. TOP COURSES FOR ALL 10 CS FUNDAMENTAL DOMAINS
// ─────────────────────────────────────────────────────────────────────────────

export const CS_FUNDAMENTALS_SUBJECTS: CsSubjectItem[] = [
  {
    id: "cs-1",
    subject: "Operating Systems",
    code: "CS-OS-201",
    category: "Systems & Architecture",
    description: "Kernel architecture, process lifecycle, thread synchronization, memory paging, file systems, and distributed OS.",
    targetDepth: "5/5 Star Mastery",
    recommendedHours: 45,
    syllabusTopics: [
      "Process Management & CPU Scheduling (FCFS, SJF, Round Robin, Multi-level Feedback)",
      "Process Synchronization, Mutexes, Semaphores & Deadlock Banker's Algorithm",
      "Memory Management: Virtual Memory, Paging, Segmentation & Page Replacement (LRU, FIFO, Clock)",
      "Storage & File Systems: Inodes, FAT, Ext4, RAID & Disk Scheduling Algorithms",
      "Linux System Calls, POSIX Threads (pthreads) & Kernel Internals",
    ],
    topCourses: [
      {
        id: "c-os-1",
        title: "Operating Systems Engineering (6.828 / 6.S081)",
        provider: "MIT OCW",
        instructor: "Prof. Frans Kaashoek & Robert Morris",
        url: "https://pdos.csail.mit.edu/6.828/2023/",
        rating: 4.9,
        enrolledStudents: "120k+",
        duration: "40 Hours",
        level: "Comprehensive",
        description: "World-class xv6 Unix OS kernel implementation in C covering interrupts, virtual memory, and file systems.",
        tags: ["MIT", "C / Assembly", "Kernel Development", "xv6"],
      },
      {
        id: "c-os-2",
        title: "Complete Operating Systems Mastery Playlist",
        provider: "Gate Smashers",
        instructor: "Varun Singla",
        url: "https://www.youtube.com/playlist?list=PLxCzCOWd7aiGz9donHRrE9I3Mwn6XdP8p",
        rating: 4.9,
        enrolledStudents: "1.4M+",
        duration: "28 Hours",
        level: "Intermediate",
        description: "Clear, exam & interview-oriented explanations of process scheduling, semaphores, paging, and memory management.",
        tags: ["Gate Smashers", "Placements", "Scheduling", "Deadlocks"],
      },
      {
        id: "c-os-3",
        title: "Introduction to Operating Systems (CS 162)",
        provider: "UC Berkeley",
        instructor: "Prof. Anthony D. Joseph",
        url: "https://cs162.org/",
        rating: 4.8,
        enrolledStudents: "95k+",
        duration: "45 Hours",
        level: "Advanced",
        description: "In-depth concurrency, Pintos OS kernel projects, distributed consensus, and file system crash consistency.",
        tags: ["UC Berkeley", "Pintos", "Concurrency", "Paging"],
      },
      {
        id: "c-os-4",
        title: "Operating System Fundamentals & Synchronization",
        provider: "NPTEL / IIT",
        instructor: "Prof. P. K. Biswas (IIT Kharagpur)",
        url: "https://nptel.ac.in/courses/106105214",
        rating: 4.7,
        enrolledStudents: "60k+",
        duration: "30 Hours",
        level: "Intermediate",
        description: "Rigorous academic curriculum on multi-threaded concurrency, resource allocation graphs, and real-time scheduling.",
        tags: ["NPTEL", "IIT Kharagpur", "Academic", "Semaphores"],
      },
    ],
  },
  {
    id: "cs-2",
    subject: "Database Management Systems",
    code: "CS-DBMS-202",
    category: "Data & Storage Engines",
    description: "Relational algebra, SQL query tuning, B+ Tree indexing, ACID transactions, WAL recovery, and NoSQL architecture.",
    targetDepth: "5/5 Star Mastery",
    recommendedHours: 40,
    syllabusTopics: [
      "Relational Model, Normalization (1NF, 2NF, 3NF, BCNF) & ER Diagrams",
      "B+ Tree, Hash Indexing, Query Optimization & Cost Estimation",
      "Transaction Processing, ACID Properties, Concurrency Control (2PL, Timestamp, MVCC)",
      "Database Recovery: Write-Ahead Logging (WAL) & ARIES Protocol",
      "Distributed Databases, CAP Theorem, Sharding & NoSQL Architecture",
    ],
    topCourses: [
      {
        id: "c-dbms-1",
        title: "Database Systems (15-445/645 - Intro to Database Systems)",
        provider: "CMU",
        instructor: "Prof. Andy Pavlo (Carnegie Mellon)",
        url: "https://15445.courses.cs.cmu.edu/",
        rating: 5.0,
        enrolledStudents: "180k+",
        duration: "48 Hours",
        level: "Comprehensive",
        description: "Legendary CMU course on relational database storage engines (BusTub), buffer pools, B+ Trees, and query executors.",
        tags: ["CMU", "Andy Pavlo", "Storage Engines", "B+ Trees"],
      },
      {
        id: "c-dbms-2",
        title: "Complete DBMS & SQL for Placements",
        provider: "Gate Smashers",
        instructor: "Varun Singla",
        url: "https://www.youtube.com/playlist?list=PLxCzCOWd7aiFAN6I8C9XdK_G65gkmHwMQ",
        rating: 4.9,
        enrolledStudents: "1.2M+",
        duration: "25 Hours",
        level: "Intermediate",
        description: "Top-rated series for interview preparation covering Normalization, SQL queries, Indexing, and Transaction schedules.",
        tags: ["Gate Smashers", "SQL", "Normalization", "ACID"],
      },
      {
        id: "c-dbms-3",
        title: "Databases: Relational Databases and SQL",
        provider: "Stanford Online",
        instructor: "Prof. Jennifer Widom",
        url: "https://online.stanford.edu/courses/soe-ydatabases-databases-relational-databases-and-sql",
        rating: 4.8,
        enrolledStudents: "250k+",
        duration: "20 Hours",
        level: "Intermediate",
        description: "Stanford's standard relational algebra, SQL DDL/DML, triggers, views, and integrity constraints.",
        tags: ["Stanford", "SQL", "Relational Algebra"],
      },
      {
        id: "c-dbms-4",
        title: "DBMS & Transaction Management",
        provider: "NPTEL / IIT",
        instructor: "Prof. Partha Pratim Das (IIT Kharagpur)",
        url: "https://nptel.ac.in/courses/106105175",
        rating: 4.7,
        enrolledStudents: "50k+",
        duration: "32 Hours",
        level: "Intermediate",
        description: "Deep dive into serializability, 2PL, isolation levels, multi-version concurrency control, and query evaluation.",
        tags: ["NPTEL", "IIT Kharagpur", "Serializability", "MVCC"],
      },
    ],
  },
  {
    id: "cs-3",
    subject: "Computer Networks",
    code: "CS-CN-203",
    category: "Networking & Protocols",
    description: "OSI/TCP-IP models, socket programming, routing algorithms, TCP congestion control, HTTP/3, and TLS 1.3.",
    targetDepth: "5/5 Star Mastery",
    recommendedHours: 35,
    syllabusTopics: [
      "Layered Architecture (OSI vs TCP/IP), Framing, CRC & Sliding Window Protocols",
      "IP Addressing (IPv4/IPv6), CIDR Subnetting, ARP, ICMP & DHCP",
      "Routing Protocols: Distance Vector (Bellman-Ford), Link State (Dijkstra/OSPF), BGP",
      "Transport Layer: TCP 3-Way Handshake, Flow Control, Congestion Control (Reno, Cubic, BBR) & UDP",
      "Application Protocols (DNS, HTTP/1.1, HTTP/2, HTTP/3, WebSocket, TLS 1.3 & WebSockets)",
    ],
    topCourses: [
      {
        id: "c-cn-1",
        title: "Computer Networks: A Systems Approach",
        provider: "Stanford Online",
        instructor: "Prof. Nick McKeown & Philip Levis",
        url: "https://web.stanford.edu/class/cs144/",
        rating: 4.9,
        enrolledStudents: "85k+",
        duration: "40 Hours",
        level: "Comprehensive",
        description: "Build a full TCP/IP stack from scratch in modern C++, including router forwarding, TCP flow, and retransmission.",
        tags: ["Stanford", "CS144", "TCP Stack", "Socket Programming"],
      },
      {
        id: "c-cn-2",
        title: "Computer Networks Complete Roadmap Playlist",
        provider: "Gate Smashers",
        instructor: "Varun Singla",
        url: "https://www.youtube.com/playlist?list=PLxCzCOWd7aiGFBD2-2joCpWOLUrDLvVV_",
        rating: 4.9,
        enrolledStudents: "1.1M+",
        duration: "24 Hours",
        level: "Intermediate",
        description: "Intuitive breakdowns of Subnetting, TCP windowing, routing algorithms, DNS resolution, and HTTP headers.",
        tags: ["Gate Smashers", "Subnetting", "TCP", "OSI"],
      },
      {
        id: "c-cn-3",
        title: "Computer Networking Course (Network Fundamentals)",
        provider: "FreeCodeCamp",
        instructor: "Kunal Kushwaha / NetworkChuck",
        url: "https://www.freecodecamp.org/news/free-computer-networking-course/",
        rating: 4.8,
        enrolledStudents: "450k+",
        duration: "15 Hours",
        level: "Beginner",
        description: "Practical packet sniffing with Wireshark, IP routing, subnet masks, DNS, and HTTP/HTTPS handshakes.",
        tags: ["FreeCodeCamp", "Wireshark", "Hands-on", "Subnets"],
      },
      {
        id: "c-cn-4",
        title: "Computer Networks & Internet Protocol",
        provider: "NPTEL / IIT",
        instructor: "Prof. Soumya Kanti Ghosh (IIT Kharagpur)",
        url: "https://nptel.ac.in/courses/106105183",
        rating: 4.7,
        enrolledStudents: "70k+",
        duration: "30 Hours",
        level: "Intermediate",
        description: "Formal academic treatment of queueing models, congestion control, wireless MAC protocols, and network security.",
        tags: ["NPTEL", "IIT Kharagpur", "Protocols", "Queueing Theory"],
      },
    ],
  },
  {
    id: "cs-4",
    subject: "System Design & Distributed Systems",
    code: "CS-SD-204",
    category: "Architecture & Scale",
    description: "High-level system design (HLD), low-level design (LLD), microservices, caching, rate limiters, consensus, and CAP theorem.",
    targetDepth: "5/5 Star Mastery",
    recommendedHours: 50,
    syllabusTopics: [
      "Scalability: Horizontal vs Vertical, Load Balancers (L4 vs L7, Round Robin, Consistent Hashing)",
      "Caching Strategies (Cache-Aside, Write-Through, Redis/Memcached) & CDN Edge",
      "Message Queues (Kafka, RabbitMQ), Event-Driven Architecture & Pub/Sub",
      "Distributed Consensus (Raft, Paxos), CAP Theorem & PACELC Tradeoffs",
      "Real-world HLD: URL Shortener, WhatsApp, Netflix, Distributed Rate Limiter & Uber",
    ],
    topCourses: [
      {
        id: "c-sd-1",
        title: "Distributed Systems (6.824)",
        provider: "MIT OCW",
        instructor: "Prof. Robert Morris",
        url: "https://pdos.csail.mit.edu/6.824/",
        rating: 5.0,
        enrolledStudents: "200k+",
        duration: "50 Hours",
        level: "Advanced",
        description: "The gold-standard distributed systems course: MapReduce, Raft consensus algorithm, multi-Paxos, and spanner databases.",
        tags: ["MIT", "Raft Consensus", "Go", "Fault Tolerance"],
      },
      {
        id: "c-sd-2",
        title: "System Design Interview Bootcamp",
        provider: "Coursera",
        instructor: "Alex Xu & Industry Experts",
        url: "https://www.coursera.org/learn/system-design",
        rating: 4.8,
        enrolledStudents: "110k+",
        duration: "25 Hours",
        level: "Intermediate",
        description: "Complete guide to designing scalable, reliable systems for Tier-1 FAANG architectural interviews.",
        tags: ["HLD", "Scalability", "Microservices", "Interviews"],
      },
      {
        id: "c-sd-3",
        title: "Distributed Systems Engineering",
        provider: "UC Berkeley",
        instructor: "Prof. Joseph M. Hellerstein",
        url: "https://cs186berkeley.net/",
        rating: 4.8,
        enrolledStudents: "75k+",
        duration: "35 Hours",
        level: "Advanced",
        description: "Deep exploration of partitioned databases, distributed transactions, 2-phase commit, and consensus.",
        tags: ["UC Berkeley", "CAP Theorem", "Consensus", "Transactions"],
      },
    ],
  },
  {
    id: "cs-5",
    subject: "Data Structures & Algorithms Theory",
    code: "CS-DSA-205",
    category: "Theory & Computation",
    description: "Asymptotic notation, Master theorem, dynamic programming optimization, tree & graph theory, flow networks, and NP-completeness.",
    targetDepth: "5/5 Star Mastery",
    recommendedHours: 50,
    syllabusTopics: [
      "Asymptotic Analysis (Big-O, Big-Omega, Theta), Recurrence Relations & Master Theorem",
      "Advanced Trees: AVL, Red-Black Trees, Segment Trees, Fenwick Trees & Tries",
      "Graph Algorithms: Dijkstra, Bellman-Ford, Floyd-Warshall, Kosaraju SCC & Max Flow",
      "Dynamic Programming Paradigms: Digit DP, Bitmask DP, Tree DP & Space Optimizations",
      "Tractable vs Intractable Problems: P, NP, NP-Complete & NP-Hard Reductions",
    ],
    topCourses: [
      {
        id: "c-dsa-1",
        title: "Introduction to Algorithms (6.006 / 6.046J)",
        provider: "MIT OCW",
        instructor: "Prof. Erik Demaine & Srini Devadas",
        url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/",
        rating: 5.0,
        enrolledStudents: "500k+",
        duration: "45 Hours",
        level: "Comprehensive",
        description: "The premier algorithms course: proof of correctness, amortized analysis, dynamic programming, and shortest paths.",
        tags: ["MIT", "Erik Demaine", "CLRS", "Asymptotics"],
      },
      {
        id: "c-dsa-2",
        title: "Algorithms & Data Structures Masterclass",
        provider: "Abdul Bari",
        instructor: "Abdul Bari",
        url: "https://www.youtube.com/playlist?list=PLDN4rrl48X7TsC8gHqg31V_M6g3P-vG4e",
        rating: 4.9,
        enrolledStudents: "2.1M+",
        duration: "35 Hours",
        level: "Intermediate",
        description: "World-renowned clear visualizations of Divide and Conquer, Greedy algorithms, Dynamic Programming, and Graph Traversals.",
        tags: ["Abdul Bari", "Visualizations", "DP", "Greedy"],
      },
      {
        id: "c-dsa-3",
        title: "Algorithms: Design and Analysis",
        provider: "Stanford Online",
        instructor: "Prof. Tim Roughgarden",
        url: "https://online.stanford.edu/courses/soe-ycsalgorithms1-algorithms-design-and-analysis-part-1",
        rating: 4.9,
        enrolledStudents: "300k+",
        duration: "30 Hours",
        level: "Advanced",
        description: "Master algorithmic thinking, randomized algorithms, graph search, Dijkstra, heaps, and NP-complete reductions.",
        tags: ["Stanford", "Tim Roughgarden", "Complexity"],
      },
    ],
  },
  {
    id: "cs-6",
    subject: "Computer Organization & Architecture",
    code: "CS-COA-206",
    category: "Hardware & Microprocessors",
    description: "Instruction set architecture (RISC vs CISC), CPU datapath, instruction pipelining, cache mapping, and superscalar execution.",
    targetDepth: "4/5 Star Mastery",
    recommendedHours: 30,
    syllabusTopics: [
      "Instruction Set Architectures (RISC-V vs MIPS vs x86-64) & Assembly Translation",
      "CPU Datapath Design, Control Unit (Hardwired vs Microprogrammed)",
      "Pipelining, Hazards (Structural, Data, Control) & Branch Prediction",
      "Memory Hierarchy: Cache Mapping (Direct, Set-Associative, Fully Associative) & Cache Coherence (MESI)",
      "Superscalar Architecture, Out-of-Order Execution & Tomasulo's Algorithm",
    ],
    topCourses: [
      {
        id: "c-coa-1",
        title: "Computer Architecture (18-447)",
        provider: "CMU",
        instructor: "Prof. Onur Mutlu",
        url: "https://safari.ethz.ch/architecture/",
        rating: 4.9,
        enrolledStudents: "80k+",
        duration: "40 Hours",
        level: "Comprehensive",
        description: "Modern computer architecture: memory controllers, branch predictors, cache hierarchies, and GPU design.",
        tags: ["CMU", "Onur Mutlu", "Microarchitecture", "Caches"],
      },
      {
        id: "c-coa-2",
        title: "Computer Organization & Architecture",
        provider: "Gate Smashers",
        instructor: "Varun Singla",
        url: "https://www.youtube.com/playlist?list=PLxCzCOWd7aiHMonh3G6QNKq53C6oNXGrX",
        rating: 4.8,
        enrolledStudents: "850k+",
        duration: "20 Hours",
        level: "Intermediate",
        description: "Pipelining, hazard calculation, cache hit/miss formulas, and IEEE 754 floating point arithmetic made simple.",
        tags: ["Gate Smashers", "Pipelining", "Cache Mapping", "Hazards"],
      },
      {
        id: "c-coa-3",
        title: "Computer Organization and Architecture",
        provider: "NPTEL / IIT",
        instructor: "Prof. Indranil Sengupta (IIT Kharagpur)",
        url: "https://nptel.ac.in/courses/106105163",
        rating: 4.7,
        enrolledStudents: "45k+",
        duration: "30 Hours",
        level: "Intermediate",
        description: "Detailed analysis of microprogramming, arithmetic logic units (ALU), DMA controllers, and bus architectures.",
        tags: ["NPTEL", "IIT Kharagpur", "ALU", "Microprogramming"],
      },
    ],
  },
  {
    id: "cs-7",
    subject: "Compiler Design & Theory of Computation",
    code: "CS-CD-207",
    category: "Theory & Languages",
    description: "Finite automata, regular grammars, context-free parsing (LL, LR, LALR), AST generation, type checking, and code optimization.",
    targetDepth: "4/5 Star Mastery",
    recommendedHours: 35,
    syllabusTopics: [
      "Automata: DFA, NFA, Regular Expressions & State Minimization (Myhill-Nerode)",
      "Context-Free Grammars, Ambiguity & Pushdown Automata (PDA)",
      "Lexical Analysis, Tokenization (Lex/Flex) & Syntax Analysis (LL(1), LR(0), SLR, LALR(1))",
      "Syntax-Directed Translation, Symbol Tables, Type Checking & Intermediate Code (3-Address Code)",
      "Code Optimization (Dead Code, Loop Unrolling, Constant Folding) & Register Allocation",
    ],
    topCourses: [
      {
        id: "c-cd-1",
        title: "Compilers (CS143)",
        provider: "Stanford Online",
        instructor: "Prof. Alex Aiken",
        url: "https://web.stanford.edu/class/cs143/",
        rating: 4.9,
        enrolledStudents: "90k+",
        duration: "35 Hours",
        level: "Comprehensive",
        description: "Stanford's famous compiler course: build a complete compiler for the COOL object-oriented language.",
        tags: ["Stanford", "CS143", "COOL Compiler", "Parsing"],
      },
      {
        id: "c-cd-2",
        title: "Theory of Computation & Automata Playlist",
        provider: "Gate Smashers",
        instructor: "Varun Singla",
        url: "https://www.youtube.com/playlist?list=PLxCzCOWd7aiFM9Lj5G9G_76adtyb4ef7i",
        rating: 4.9,
        enrolledStudents: "950k+",
        duration: "22 Hours",
        level: "Intermediate",
        description: "Comprehensive lessons on DFA construction, NFA-to-DFA conversion, CFGs, Turing machines, and Chomsky hierarchy.",
        tags: ["Gate Smashers", "TOC", "Automata", "Turing Machines"],
      },
      {
        id: "c-cd-3",
        title: "Principles of Compiler Design",
        provider: "NPTEL / IIT",
        instructor: "Prof. Santanu Chattopadhyay (IIT Kharagpur)",
        url: "https://nptel.ac.in/courses/106105190",
        rating: 4.6,
        enrolledStudents: "35k+",
        duration: "30 Hours",
        level: "Advanced",
        description: "In-depth mathematical foundations of LR parsing, DAG generation, control flow graphs, and dataflow equations.",
        tags: ["NPTEL", "IIT Kharagpur", "Dataflow Analysis", "AST"],
      },
    ],
  },
  {
    id: "cs-8",
    subject: "Software Engineering & OOD",
    code: "CS-SE-208",
    category: "Software Engineering",
    description: "Agile methodologies, UML diagrams, SOLID design principles, clean code patterns, TDD, and CI/CD pipelines.",
    targetDepth: "5/5 Star Mastery",
    recommendedHours: 30,
    syllabusTopics: [
      "Software Development Life Cycles (Agile, Scrum, Kanban, Waterfall) & Estimation",
      "UML Modeling: Class Diagrams, Sequence Diagrams, State Machines & Activity Diagrams",
      "SOLID Principles (SRP, OCP, LSP, ISP, DIP) with Clean Code Refactoring",
      "Creational, Structural & Behavioral Design Patterns (Factory, Strategy, Observer, Decorator)",
      "Test-Driven Development (TDD), Code Smells, Static Code Analysis & CI/CD",
    ],
    topCourses: [
      {
        id: "c-se-1",
        title: "Software Engineering: Design Patterns & Architecture",
        provider: "Coursera",
        instructor: "University of Alberta",
        url: "https://www.coursera.org/specializations/software-design-architecture",
        rating: 4.8,
        enrolledStudents: "140k+",
        duration: "30 Hours",
        level: "Intermediate",
        description: "Practical application of SOLID principles, Gang of Four (GoF) design patterns, and microservices architecture.",
        tags: ["SOLID", "Design Patterns", "UML", "Architecture"],
      },
      {
        id: "c-se-2",
        title: "CS50 Software Engineering & Web Development",
        provider: "Harvard CS50",
        instructor: "Prof. David J. Malan",
        url: "https://cs50.harvard.edu/web/",
        rating: 4.9,
        enrolledStudents: "600k+",
        duration: "35 Hours",
        level: "Beginner",
        description: "Harvard's project-driven software engineering: CI/CD, Git workflows, database migrations, and testing.",
        tags: ["Harvard", "CS50", "Testing", "CI/CD"],
      },
    ],
  },
  {
    id: "cs-9",
    subject: "Cyber Security & Cryptography",
    code: "CS-SEC-209",
    category: "Security & Encryption",
    description: "Symmetric & asymmetric cryptography (AES, RSA, ECC), PKI, TLS/SSL, web vulnerabilities (OWASP Top 10), and authentication (OAuth/JWT).",
    targetDepth: "5/5 Star Mastery",
    recommendedHours: 35,
    syllabusTopics: [
      "Classical & Modern Cryptography: AES, DES, RSA, Elliptic Curve Cryptography (ECC)",
      "Hash Functions (SHA-256), HMAC, Digital Signatures & Public Key Infrastructure (PKI)",
      "Network Security: TLS 1.3 Handshake, Cipher Suites, IPSec & VPN Protocols",
      "Web Application Security: SQL Injection, XSS, CSRF, SSRF & OWASP Top 10 Mitigations",
      "Authentication Protocols: OAuth 2.0, OpenID Connect (OIDC), JWT & Multi-Factor Auth",
    ],
    topCourses: [
      {
        id: "c-sec-1",
        title: "Cryptography I",
        provider: "Stanford Online",
        instructor: "Prof. Dan Boneh",
        url: "https://online.stanford.edu/courses/soe-ycryptography-cryptography-i",
        rating: 5.0,
        enrolledStudents: "350k+",
        duration: "30 Hours",
        level: "Advanced",
        description: "The world's most famous cryptography course: block ciphers, authenticated encryption, RSA, and zero-knowledge proofs.",
        tags: ["Stanford", "Dan Boneh", "AES", "RSA", "ECC"],
      },
      {
        id: "c-sec-2",
        title: "Computer Systems Security (6.858)",
        provider: "MIT OCW",
        instructor: "Prof. Nickolai Zeldovich",
        url: "https://css.csail.mit.edu/6.858/2022/",
        rating: 4.9,
        enrolledStudents: "110k+",
        duration: "40 Hours",
        level: "Comprehensive",
        description: "Hands-on buffer overflow exploits, return-oriented programming (ROP), isolation sandboxing, and web security.",
        tags: ["MIT", "Binary Exploitation", "ROP", "Web Security"],
      },
      {
        id: "c-sec-3",
        title: "Information Security and Cryptography",
        provider: "NPTEL / IIT",
        instructor: "Prof. Sourav Mukhopadhyay (IIT Kharagpur)",
        url: "https://nptel.ac.in/courses/106105031",
        rating: 4.7,
        enrolledStudents: "40k+",
        duration: "30 Hours",
        level: "Intermediate",
        description: "Mathematical rigor behind discrete logarithms, Diffie-Hellman, stream ciphers, and cryptanalysis.",
        tags: ["NPTEL", "IIT Kharagpur", "Diffie-Hellman", "Math"],
      },
    ],
  },
  {
    id: "cs-10",
    subject: "Cloud Computing & Distributed Systems",
    code: "CS-CLOUD-210",
    category: "Cloud & Infrastructure",
    description: "Cloud virtualization, containerization (Docker/K8s), distributed consensus, object/block storage, and serverless architectures.",
    targetDepth: "5/5 Star Mastery",
    recommendedHours: 35,
    syllabusTopics: [
      "Virtualization & Container Internals: Linux Namespaces, Cgroups, Hypervisors & Docker",
      "Container Orchestration: Kubernetes Pods, Deployments, Services & Ingress Controllers",
      "Cloud Storage Models: Object (S3), Block (EBS), File (EFS) & Distributed File Systems (HDFS/Ceph)",
      "Distributed Consensus: Raft vs Paxos, Byzantine Fault Tolerance & Vector Clocks",
      "Serverless Computing (AWS Lambda / Cloud Functions), Cold Starts & Cloud Cost Optimization (FinOps)",
    ],
    topCourses: [
      {
        id: "c-cloud-1",
        title: "Cloud Computing Concepts",
        provider: "Coursera",
        instructor: "Prof. Indranil Gupta (UIUC)",
        url: "https://www.coursera.org/learn/cloud-computing",
        rating: 4.8,
        enrolledStudents: "220k+",
        duration: "30 Hours",
        level: "Comprehensive",
        description: "Peer-to-peer protocols, Gossip algorithms, distributed key-value stores (Cassandra/Dynamo), and MapReduce.",
        tags: ["UIUC", "Gossip Protocols", "Cassandra", "MapReduce"],
      },
      {
        id: "c-cloud-2",
        title: "Introduction to Cloud Computing",
        provider: "NPTEL / IIT",
        instructor: "Prof. Soumya K. Ghosh (IIT Kharagpur)",
        url: "https://nptel.ac.in/courses/106105167",
        rating: 4.7,
        enrolledStudents: "65k+",
        duration: "25 Hours",
        level: "Intermediate",
        description: "SaaS/PaaS/IaaS architectures, cloud SLAs, virtualization security, and open-source OpenStack deployment.",
        tags: ["NPTEL", "IIT Kharagpur", "Virtualization", "SLA"],
      },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// 2. 200 QUIZZES CATALOG WITH 3 SECTIONS: EASY, MEDIUM, AND HARD
// ─────────────────────────────────────────────────────────────────────────────

const DOMAIN_QUIZ_BLUEPRINTS: Record<string, { topic: string; sub: string }[]> = {
  "cs-1": [
    { topic: "Process Lifecycle, States & PCB Internals", sub: "Processes & Threads" },
    { topic: "CPU Scheduling: FCFS, SJF, SRTF & Priority", sub: "CPU Scheduling" },
    { topic: "Round Robin & Multi-Level Feedback Queues", sub: "CPU Scheduling" },
    { topic: "Thread Synchronization & Race Conditions", sub: "Concurrency" },
    { topic: "Mutexes, Semaphores & Peterson's Algorithm", sub: "Concurrency" },
    { topic: "Classical Concurrency: Producer-Consumer & Readers-Writers", sub: "Concurrency" },
    { topic: "Dining Philosophers & Deadlock Characterization", sub: "Deadlocks" },
    { topic: "Deadlock Prevention, Avoidance & Banker's Algorithm", sub: "Deadlocks" },
    { topic: "Memory Hierarchy, Address Binding & Protection", sub: "Memory Management" },
    { topic: "Paging Architecture & Page Table Structures", sub: "Memory Management" },
    { topic: "Inverted Page Tables & Translation Lookaside Buffers (TLB)", sub: "Memory Management" },
    { topic: "Virtual Memory, Demand Paging & Page Fault Handling", sub: "Virtual Memory" },
    { topic: "Page Replacement Algorithms: FIFO, Optimal & LRU", sub: "Virtual Memory" },
    { topic: "Clock / Second-Chance & Working Set Model (Thrashing)", sub: "Virtual Memory" },
    { topic: "File System Structure: Inodes, Superblocks & Dentry", sub: "File Systems" },
    { topic: "File Allocation Methods: Contiguous, Linked & Indexed", sub: "File Systems" },
    { topic: "Disk Scheduling: FCFS, SSTF, SCAN, C-SCAN & LOOK", sub: "I/O & Storage" },
    { topic: "Linux System Calls, fork(), exec(), wait() & POSIX", sub: "Linux Internals" },
    { topic: "Inter-Process Communication: Pipes, Message Queues & Shared Memory", sub: "IPC" },
    { topic: "Real-Time Operating Systems (RTOS) & Rate Monotonic Scheduling", sub: "Advanced OS" },
  ],
  "cs-2": [
    { topic: "Relational Data Model & Relational Algebra Operators", sub: "Relational Theory" },
    { topic: "Tuple Relational Calculus & Domain Relational Calculus", sub: "Relational Theory" },
    { topic: "Entity-Relationship (ER) Modeling & Constraint Mapping", sub: "Database Design" },
    { topic: "Functional Dependencies & Attribute Closure Algorithms", sub: "Normalization" },
    { topic: "Normalization: 1NF, 2NF & 3NF Lossless Decomposition", sub: "Normalization" },
    { topic: "Boyce-Codd Normal Form (BCNF) & 4NF Multi-Valued Dependencies", sub: "Normalization" },
    { topic: "Advanced SQL: Window Functions, CTEs & Recursive Queries", sub: "SQL & Querying" },
    { topic: "B-Tree & B+ Tree File Organization and Split Mechanisms", sub: "Indexing & Storage" },
    { topic: "Static & Dynamic Hashing (Extendible & Linear Hashing)", sub: "Indexing & Storage" },
    { topic: "Query Evaluation Engine, Joins (Hash, Merge, Nested Loop)", sub: "Query Execution" },
    { topic: "Query Optimizer, Cost Estimation & EXPLAIN Plans", sub: "Query Optimization" },
    { topic: "Transaction Concept, ACID Properties & State Transitions", sub: "Transactions" },
    { topic: "Serializability: Conflict Serializability & Precedence Graphs", sub: "Concurrency Control" },
    { topic: "View Serializability & Strict Schedule Properties", sub: "Concurrency Control" },
    { topic: "Lock-Based Protocols: Two-Phase Locking (2PL, Strict, Rigorous)", sub: "Concurrency Control" },
    { topic: "Timestamp Ordering Protocols & Thomas Write Rule", sub: "Concurrency Control" },
    { topic: "Multi-Version Concurrency Control (MVCC) & Snapshot Isolation", sub: "Concurrency Control" },
    { topic: "Database Recovery: Log-Based Recovery, WAL & Checkpointing", sub: "Crash Recovery" },
    { topic: "ARIES Recovery Algorithm: Analysis, Redo & Undo Phases", sub: "Crash Recovery" },
    { topic: "Distributed Databases, 2-Phase Commit (2PC) & CAP Theorem", sub: "Distributed DBMS" },
  ],
  "cs-3": [
    { topic: "OSI Reference Model vs TCP/IP Protocol Suite", sub: "Network Models" },
    { topic: "Physical Layer: Transmission Media, Nyquist & Shannon Capacity", sub: "Physical Layer" },
    { topic: "Data Link Layer: Framing, Bit Stuffing & Error Detection (CRC)", sub: "Data Link Layer" },
    { topic: "Flow Control Protocols: Stop-and-Wait, Go-Back-N & Selective Repeat", sub: "Data Link Layer" },
    { topic: "Medium Access Control: ALOHA, CSMA/CD & CSMA/CA (Wi-Fi)", sub: "MAC Sublayer" },
    { topic: "Ethernet Standards, Switching, VLANs & Spanning Tree (STP)", sub: "LAN Technologies" },
    { topic: "Network Layer: IPv4 Header Format, Options & Fragmentation", sub: "IPv4 Addressing" },
    { topic: "IPv4 Subnetting, VLSM & Classless Inter-Domain Routing (CIDR)", sub: "IP Subnetting" },
    { topic: "IPv6 Header, Dual Stacking & Stateless Address Autoconfig (SLAAC)", sub: "IPv6 Architecture" },
    { topic: "Address Resolution Protocol (ARP), RARP & Gratuitous ARP", sub: "Network Layer" },
    { topic: "Internet Control Message Protocol (ICMP) & Traceroute Internals", sub: "Network Layer" },
    { topic: "Routing Algorithms: Bellman-Ford Distance Vector & Count to Infinity", sub: "Routing" },
    { topic: "Link State Routing (Dijkstra) & Open Shortest Path First (OSPF)", sub: "Routing" },
    { topic: "Border Gateway Protocol (BGP), AS Paths & Policy Routing", sub: "Routing" },
    { topic: "Transport Layer: UDP Header & Connectionless Semantics", sub: "Transport Layer" },
    { topic: "TCP Connection Management: 3-Way Handshake & 4-Way Teardown", sub: "TCP Protocol" },
    { topic: "TCP Flow Control: Sliding Window, Silly Window Syndrome & Nagle", sub: "TCP Protocol" },
    { topic: "TCP Congestion Control: Slow Start, Tahoe, Reno & Cubic", sub: "TCP Protocol" },
    { topic: "Domain Name System (DNS): Iterative vs Recursive Querying & DNSSEC", sub: "Application Layer" },
    { topic: "Web Protocols: HTTP/1.1, HTTP/2 Multiplexing, HTTP/3 (QUIC) & TLS 1.3", sub: "Web Architecture" },
  ],
  "cs-4": [
    { topic: "Vertical vs Horizontal Scaling & Single Point of Failure (SPOF)", sub: "Scalability" },
    { topic: "Load Balancing Algorithms: Round Robin, Weighted, IP Hash & L4/L7", sub: "Load Balancing" },
    { topic: "Consistent Hashing & Virtual Nodes Partitioning", sub: "Distributed Hash" },
    { topic: "Caching Architectures: Cache-Aside, Read-Through, Write-Through & Write-Back", sub: "Caching" },
    { topic: "Distributed Cache Eviction (LRU, LFU) & Cache Stampede Mitigation", sub: "Caching" },
    { topic: "Message Queues & Broker Internals (Kafka Partitions vs RabbitMQ AMQP)", sub: "Messaging" },
    { topic: "Event-Driven Architecture, Pub-Sub & Dead Letter Queues", sub: "Messaging" },
    { topic: "Database Replication: Leader-Follower, Multi-Leader & Quorum Reads/Writes", sub: "Databases" },
    { topic: "Database Sharding Strategies: Range, Hash, Directory & Rebalancing", sub: "Databases" },
    { topic: "CAP Theorem & PACELC Trade-Offs in Production Systems", sub: "Distributed Theory" },
    { topic: "Distributed Consensus: Raft Protocol (Leader Election & Log Replication)", sub: "Consensus" },
    { topic: "Distributed Transactions: Two-Phase Commit (2PC) & Saga Orchestration", sub: "Transactions" },
    { topic: "API Gateway Architecture, Reverse Proxies & Service Mesh (Envoy)", sub: "Microservices" },
    { topic: "Distributed Rate Limiting: Token Bucket, Leaky Bucket & Sliding Window", sub: "Resilience" },
    { topic: "Resilience Patterns: Circuit Breaker, Bulkhead, Fallback & Retries", sub: "Resilience" },
    { topic: "System Design Case Study: Scalable URL Shortener (TinyURL)", sub: "Case Studies" },
    { topic: "System Design Case Study: Real-Time Chat System (WhatsApp / Slack)", sub: "Case Studies" },
    { topic: "System Design Case Study: Video Streaming Platform (YouTube / Netflix)", sub: "Case Studies" },
    { topic: "System Design Case Study: Distributed Key-Value Store (Dynamo-Style)", sub: "Case Studies" },
    { topic: "Distributed Tracing, Log Aggregation & Observability (OpenTelemetry)", sub: "Observability" },
  ],
  "cs-5": [
    { topic: "Asymptotic Notations: Big-O, Big-Omega, Big-Theta, Little-o & Little-omega", sub: "Asymptotics" },
    { topic: "Recurrence Relations: Substitution & Recursion Tree Methods", sub: "Recurrences" },
    { topic: "Master Theorem & Akra-Bazzi Generalization for Divide-and-Conquer", sub: "Recurrences" },
    { topic: "Amortized Complexity Analysis: Aggregate, Accounting & Potential Method", sub: "Amortized Analysis" },
    { topic: "Balanced BSTs: AVL Tree Rotations & Height Proofs", sub: "Advanced Trees" },
    { topic: "Red-Black Trees: Properties, Insertion/Deletion Color Fixups", sub: "Advanced Trees" },
    { topic: "Segment Trees & Lazy Propagation for Range Minimum/Sum Queries", sub: "Advanced Trees" },
    { topic: "Binary Indexed Trees (Fenwick Trees) for Prefix Updates & Queries", sub: "Advanced Trees" },
    { topic: "Disjoint Set Union (DSU) with Union by Rank & Path Compression (Ackermann)", sub: "Graph Primitives" },
    { topic: "Shortest Path Algorithms: Dijkstra, Bellman-Ford & Negative Cycles", sub: "Graph Algorithms" },
    { topic: "All-Pairs Shortest Path: Floyd-Warshall & Johnson's Reweighting Algorithm", sub: "Graph Algorithms" },
    { topic: "Minimum Spanning Trees: Kruskal, Prim & Cut Property Proofs", sub: "Graph Algorithms" },
    { topic: "Network Flow: Ford-Fulkerson, Edmonds-Karp & Max-Flow Min-Cut Theorem", sub: "Flow Networks" },
    { topic: "String Matching: Knuth-Morris-Pratt (KMP) Failure Function & Z-Algorithm", sub: "String Theory" },
    { topic: "Rabin-Karp Rolling Hash & Suffix Automata / Tries", sub: "String Theory" },
    { topic: "Dynamic Programming Optimizations: Convex Hull Trick & Divide & Conquer DP", sub: "Advanced DP" },
    { topic: "Tree DP & Re-rooting Techniques for Tree Diameters and Subtrees", sub: "Advanced DP" },
    { topic: "NP-Completeness: Polynomial Time Reductions & Cook-Levin Theorem", sub: "Complexity Theory" },
    { topic: "Classic NP-Complete Problems: 3-SAT, Vertex Cover, Clique & Hamiltonian Cycle", sub: "Complexity Theory" },
    { topic: "Probabilistic Data Structures: Bloom Filters, HyperLogLog & Count-Min Sketch", sub: "Probabilistic DS" },
  ],
  "cs-6": [
    { topic: "Number Systems, Two's Complement & Booth's Multiplication Algorithm", sub: "Computer Arithmetic" },
    { topic: "IEEE 754 Floating-Point Standard (Single & Double Precision)", sub: "Computer Arithmetic" },
    { topic: "Combinational & Sequential Circuits: Adders, Multiplexers & Flip-Flops", sub: "Digital Logic" },
    { topic: "Instruction Set Architecture: Instruction Formats, Addressing Modes (RISC vs CISC)", sub: "ISA" },
    { topic: "Single-Cycle CPU Datapath & Control Signal Generation", sub: "Datapath" },
    { topic: "Multi-Cycle CPU Datapath & Microprogrammed Control Units", sub: "Datapath" },
    { topic: "Instruction Pipelining: 5-Stage Classic MIPS Pipeline Stages", sub: "Pipelining" },
    { topic: "Pipeline Hazards: Structural Hazards & Resource Stalls", sub: "Pipelining" },
    { topic: "Data Hazards, Forwarding/Bypassing & Load-Use Stalls", sub: "Pipelining" },
    { topic: "Control Hazards, Delayed Branching & Branch Penalty Calculation", sub: "Pipelining" },
    { topic: "Dynamic Branch Prediction: 2-Bit Saturating Counters & Branch Target Buffer (BTB)", sub: "Pipelining" },
    { topic: "Memory Hierarchy & Locality of Reference (Temporal & Spatial)", sub: "Memory System" },
    { topic: "Direct-Mapped Cache Organization & Index/Tag/Offset Calculations", sub: "Cache Architecture" },
    { topic: "Set-Associative & Fully Associative Caches & Replacement Policies", sub: "Cache Architecture" },
    { topic: "Cache Write Policies: Write-Through, Write-Back, Write-Allocate", sub: "Cache Architecture" },
    { topic: "Average Memory Access Time (AMAT) & Multi-Level Cache Calculations", sub: "Memory System" },
    { topic: "Virtual Memory Hardware: TLB Structure, Page Table Walk & Miss Latency", sub: "Virtual Memory" },
    { topic: "I/O Subsystems: Programmed I/O, Interrupt-Driven I/O & Direct Memory Access (DMA)", sub: "I/O Architecture" },
    { topic: "Multiprocessor Cache Coherence: MESI, MOESI & Snooping Protocols", sub: "Parallel Architecture" },
    { topic: "Superscalar Execution, Instruction-Level Parallelism (ILP) & Tomasulo's Algorithm", sub: "Advanced Architecture" },
  ],
  "cs-7": [
    { topic: "Deterministic Finite Automata (DFA) Construction & State Transition Tables", sub: "Automata" },
    { topic: "Nondeterministic Finite Automata (NFA) & Subset Construction Algorithm", sub: "Automata" },
    { topic: "Regular Expressions, Thompson's Construction & DFA State Minimization", sub: "Automata" },
    { topic: "Pumping Lemma for Regular Languages & Non-Regularity Proofs", sub: "Formal Languages" },
    { topic: "Context-Free Grammars (CFG), Derivation Trees & Ambiguity Resolution", sub: "CFG" },
    { topic: "Chomsky Normal Form (CNF) & Greibach Normal Form (GNF) Conversion", sub: "CFG" },
    { topic: "Pushdown Automata (PDA): Acceptance by Final State vs Empty Stack", sub: "PDA" },
    { topic: "Turing Machine Architecture, Decidability & The Halting Problem", sub: "Computability" },
    { topic: "Chomsky Hierarchy: Regular, Context-Free, Context-Sensitive & Recursive Languages", sub: "Formal Languages" },
    { topic: "Compiler Architecture & Pipeline Phases: Frontend vs Backend", sub: "Compiler Overview" },
    { topic: "Lexical Analysis: Token, Pattern, Lexeme & Lex/Flex Specification", sub: "Lexical Analysis" },
    { topic: "Top-Down Parsing: Recursive Descent & LL(1) First and Follow Sets", sub: "Syntax Analysis" },
    { topic: "LL(1) Parsing Table Construction & Error Recovery Strategies", sub: "Syntax Analysis" },
    { topic: "Bottom-Up Parsing: Shift-Reduce Parsing & LR(0) Item Sets", sub: "Syntax Analysis" },
    { topic: "Simple LR (SLR(1)) Parsing Table Construction & Conflicts", sub: "Syntax Analysis" },
    { topic: "Canonical LR (LR(1)) & Lookahead LR (LALR(1)) Parsing Tables", sub: "Syntax Analysis" },
    { topic: "Syntax-Directed Translation (SDT): S-Attributed vs L-Attributed Definitions", sub: "Semantic Analysis" },
    { topic: "Intermediate Code Generation: Three-Address Code, Quadruples & Triples", sub: "Intermediate Code" },
    { topic: "Control Flow Graphs, Basic Blocks & Loop Invariant Code Motion", sub: "Code Optimization" },
    { topic: "Register Allocation via Graph Coloring (Chaitin's Algorithm) & Code Generation", sub: "Code Generation" },
  ],
  "cs-8": [
    { topic: "Software Development Life Cycles: Waterfall, Spiral, V-Model & Agile", sub: "SDLC" },
    { topic: "Agile Methodologies: Scrum Ceremonies, Sprints, User Stories & Story Points", sub: "Agile" },
    { topic: "Kanban System: Work in Progress (WIP) Limits & Cycle Time Optimization", sub: "Agile" },
    { topic: "Requirements Engineering: Functional, Non-Functional & SRS Document Standards", sub: "Requirements" },
    { topic: "UML Class Diagrams: Association, Aggregation, Composition & Generalization", sub: "UML Modeling" },
    { topic: "UML Sequence Diagrams, Lifelines, Synchronous vs Asynchronous Messages", sub: "UML Modeling" },
    { topic: "SOLID: Single Responsibility & Open/Closed Principle Deep Dive", sub: "SOLID Principles" },
    { topic: "SOLID: Liskov Substitution, Interface Segregation & Dependency Inversion", sub: "SOLID Principles" },
    { topic: "Creational Patterns: Singleton (Thread-Safe Double-Checked) & Factory Method", sub: "Design Patterns" },
    { topic: "Creational Patterns: Abstract Factory, Builder & Prototype", sub: "Design Patterns" },
    { topic: "Structural Patterns: Adapter, Facade & Decorator Patterns", sub: "Design Patterns" },
    { topic: "Structural Patterns: Proxy, Composite & Flyweight Patterns", sub: "Design Patterns" },
    { topic: "Behavioral Patterns: Observer, Strategy & Command Patterns", sub: "Design Patterns" },
    { topic: "Behavioral Patterns: Chain of Responsibility, State & Template Method", sub: "Design Patterns" },
    { topic: "Refactoring Code Smells: Long Method, Feature Envy & Shotgun Surgery", sub: "Clean Code" },
    { topic: "Test-Driven Development (TDD) Cycle: Red, Green, Refactor", sub: "Testing & QA" },
    { topic: "Software Testing Levels: Unit, Integration, System & Acceptance Testing", sub: "Testing & QA" },
    { topic: "White-Box Testing: Statement, Branch, Condition & Path Coverage", sub: "Testing & QA" },
    { topic: "Continuous Integration & Continuous Deployment (CI/CD) Pipeline Architecture", sub: "DevOps / SRE" },
    { topic: "Technical Debt Management, Software Metrics (Cyclomatic Complexity) & Cohesion", sub: "Software Quality" },
  ],
  "cs-9": [
    { topic: "Information Security Principles: CIA Triad & Threat Modeling", sub: "Security Fundamentals" },
    { topic: "Classical Cryptography: Caesar, Vigenère & One-Time Pad Proofs", sub: "Classical Crypto" },
    { topic: "Symmetric Encryption: Data Encryption Standard (DES) & 3DES", sub: "Symmetric Crypto" },
    { topic: "Advanced Encryption Standard (AES): Substitution-Permutation Network & S-Box", sub: "Symmetric Crypto" },
    { topic: "Block Cipher Modes: ECB, CBC, CFB, OFB & Galois/Counter Mode (GCM)", sub: "Block Ciphers" },
    { topic: "Cryptographic Hash Functions: Properties, MD5 Flaws & SHA-256 / SHA-3", sub: "Hash Functions" },
    { topic: "Message Authentication Codes (HMAC) & Authenticated Encryption (AEAD)", sub: "Authentication" },
    { topic: "Asymmetric Cryptography: RSA Algorithm & Prime Generation", sub: "Asymmetric Crypto" },
    { topic: "Diffie-Hellman Key Exchange & Man-in-the-Middle (MITM) Mitigations", sub: "Key Exchange" },
    { topic: "Elliptic Curve Cryptography (ECC): ECDSA & Curve25519 Speed/Security", sub: "Asymmetric Crypto" },
    { topic: "Public Key Infrastructure (PKI): X.509 Certificates & Certificate Authorities (CA)", sub: "PKI" },
    { topic: "Transport Layer Security (TLS 1.3): Handshake Protocol & Forward Secrecy", sub: "TLS / Network Sec" },
    { topic: "Authentication Protocols: OAuth 2.0 Authorization Code Flow & OpenID Connect", sub: "Auth & Identity" },
    { topic: "JSON Web Tokens (JWT): Structure, Signature Verification & Common Vulnerabilities", sub: "Auth & Identity" },
    { topic: "Multi-Factor Authentication (MFA): TOTP (RFC 6238) & FIDO2 / WebAuthn", sub: "Auth & Identity" },
    { topic: "Web Vulnerabilities: SQL Injection (SQLi) & Parameterized Queries", sub: "OWASP Top 10" },
    { topic: "Web Vulnerabilities: Cross-Site Scripting (XSS) & Content Security Policy (CSP)", sub: "OWASP Top 10" },
    { topic: "Web Vulnerabilities: Cross-Site Request Forgery (CSRF) & SameSite Cookies", sub: "OWASP Top 10" },
    { topic: "System Exploits: Buffer Overflow, Stack Smashing, ASLR & DEP/NX Bit Protections", sub: "Binary Security" },
    { topic: "Zero Trust Architecture, Least Privilege Principle & Cryptographic Key Management (HSM)", sub: "Enterprise Sec" },
  ],
  "cs-10": [
    { topic: "Cloud Computing Service Models: IaaS vs PaaS vs SaaS vs FaaS", sub: "Cloud Models" },
    { topic: "Cloud Deployment Models: Public, Private, Hybrid & Multi-Cloud Strategies", sub: "Cloud Models" },
    { topic: "Virtualization Technology: Type-1 (Bare Metal) vs Type-2 Hypervisors (KVM, Xen)", sub: "Virtualization" },
    { topic: "Linux Containers: Namespaces (PID, Mount, Net) & Control Groups (Cgroups)", sub: "Containers" },
    { topic: "Docker Architecture: Dockerfile, Image Layers, Container Runtime & Daemon", sub: "Containers" },
    { topic: "Kubernetes Architecture: Control Plane (API Server, etcd, Scheduler) & Worker Nodes", sub: "Kubernetes" },
    { topic: "Kubernetes Objects: Pods, ReplicaSets, Deployments & Rolling Updates", sub: "Kubernetes" },
    { topic: "Kubernetes Networking: ClusterIP, NodePort, LoadBalancer & Ingress Controllers", sub: "Kubernetes" },
    { topic: "Cloud Storage Models: Object Storage (S3 / Blob) vs Block (EBS) vs File (EFS)", sub: "Cloud Storage" },
    { topic: "Distributed File Systems: Google File System (GFS) & Hadoop Distributed File System (HDFS)", sub: "Distributed Storage" },
    { topic: "Distributed Consensus: Paxos Algorithm (Proposers, Acceptors, Learners)", sub: "Consensus" },
    { topic: "Distributed Consensus: Raft Protocol (Log Matching & Safety Invariant)", sub: "Consensus" },
    { topic: "Byzantine Fault Tolerance (BFT) & Practical Byzantine Fault Tolerance (PBFT)", sub: "Consensus" },
    { topic: "Time and State in Distributed Systems: Lamport Logical Clocks & Vector Clocks", sub: "Time & Clocks" },
    { topic: "Distributed Transactions: Two-Phase Commit (2PC) vs Three-Phase Commit (3PC)", sub: "Transactions" },
    { topic: "Saga Pattern: Choreography vs Orchestration for Distributed Microservices", sub: "Microservices" },
    { topic: "Cloud Networking: Virtual Private Cloud (VPC), Subnets, NAT Gateway & Direct Connect", sub: "Cloud Network" },
    { topic: "Serverless Computing: AWS Lambda Event Triggers, Concurrency & Cold Start Mitigation", sub: "Serverless" },
    { topic: "Infrastructure as Code (IaC): Declarative vs Imperative, Terraform State & Drift", sub: "IaC & DevOps" },
    { topic: "Cloud Observability & FinOps: Multi-Region High Availability & Cost Optimization", sub: "Cloud Operations" },
  ],
};

export function generateAll200CsQuizzes(): CsQuizItem[] {
  const quizzes: CsQuizItem[] = [];
  let globalQuizNumber = 1;

  for (const subject of CS_FUNDAMENTALS_SUBJECTS) {
    const subjectBlueprints = DOMAIN_QUIZ_BLUEPRINTS[subject.id] || [];

    subjectBlueprints.forEach((bp) => {
      const quizId = `cs-quiz-${globalQuizNumber}`;

      // Section 1: 5 Easy Questions
      const section1Easy: CsQuizMcqQuestion[] = [
        {
          id: `${quizId}-s1-q1`,
          question: `Which fundamental principle governs "${bp.topic}" in ${subject.subject}?`,
          options: [
            `Deterministic state transitions and optimal resource scheduling`,
            `Randomized memory allocation without synchronization`,
            `Unbounded thread execution without lock verification`,
            `Ignoring underlying kernel or hardware boundary limits`,
          ],
          correctIndex: 0,
          explanation: `In ${subject.subject}, "${bp.topic}" relies strictly on deterministic state management and efficient resource scheduling.`,
          difficulty: "Easy",
        },
        {
          id: `${quizId}-s1-q2`,
          question: `What is the primary benefit of applying standardized models to ${bp.sub}?`,
          options: [
            `Eliminating all hardware dependencies completely`,
            `Providing modularity, clear abstraction layers, and predictable performance`,
            `Increasing CPU clock cycle latency intentionally`,
            `Preventing any future software updates or extensions`,
          ],
          correctIndex: 1,
          explanation: `Standardized abstractions in ${bp.sub} guarantee modular isolation and predictable, verified runtime behavior.`,
          difficulty: "Easy",
        },
        {
          id: `${quizId}-s1-q3`,
          question: `In standard academic and industry engineering definitions, what is the best-case time/space characteristic expected for core ${bp.topic} operations?`,
          options: [
            `O(1) to O(log N) average execution bound`,
            `O(N!) factorial computational complexity`,
            `O(2^N) exponential resource consumption`,
            `Unpredictable unbounded processing delay`,
          ],
          correctIndex: 0,
          explanation: `Efficient implementations in ${subject.subject} maintain optimal logarithmic or constant-time bounds for core lookups and operations.`,
          difficulty: "Easy",
        },
        {
          id: `${quizId}-s1-q4`,
          question: `Which of the following is considered a direct violation or anti-pattern in ${bp.sub}?`,
          options: [
            `Proper encapsulation and bounded resource limits`,
            `Unchecked race conditions and lack of idempotency/synchronization`,
            `Graceful error handling with fallback states`,
            `Maintaining log consistency and atomic state transitions`,
          ],
          correctIndex: 1,
          explanation: `Race conditions and uncoordinated concurrent mutations directly violate consistency and reliability invariants.`,
          difficulty: "Easy",
        },
        {
          id: `${quizId}-s1-q5`,
          question: `When initializing or configuring ${bp.topic}, what is the recommended best practice?`,
          options: [
            `Allocate fixed infinite buffers blindly`,
            `Validate invariants, configure explicit boundary thresholds, and monitor state transitions`,
            `Disable all logging and telemetry output`,
            `Run in kernel mode with root privileges unconditionally`,
          ],
          correctIndex: 1,
          explanation: `Proper verification of boundary invariants and explicit threshold management ensures high availability and safety.`,
          difficulty: "Easy",
        },
      ];

      // Section 2: 5 Medium Questions
      const section2Medium: CsQuizMcqQuestion[] = [
        {
          id: `${quizId}-s2-q1`,
          question: `Consider a production scenario involving ${bp.topic}. A sudden throughput surge causes latency spikes. Which architectural optimization directly mitigates this bottleneck?`,
          options: [
            `Introducing non-blocking asynchronous processing and adaptive pooling`,
            `Doubling synchronous blocking thread waits across the pipeline`,
            `Disabling buffer caches and forcing continuous disk writes`,
            `Dropping all incoming transactions without acknowledgment`,
          ],
          correctIndex: 0,
          explanation: `Asynchronous I/O, event loops, and adaptive connection/resource pooling prevent thread exhaustion during high load.`,
          difficulty: "Medium",
        },
        {
          id: `${quizId}-s2-q2`,
          question: `How does ${bp.sub} handle edge-case failure modes when one node or worker process terminates unexpectedly?`,
          options: [
            `It cascades failure to the entire cluster immediately`,
            `Through heartbeat health checks, state reconciliation, and automated leader election / failover`,
            `By freezing all ongoing execution indefinitely`,
            `By deleting all persisted disk records`,
          ],
          correctIndex: 1,
          explanation: `Fault tolerance in ${subject.subject} relies on consensus-backed health monitoring, isolated worker restart, and state recovery.`,
          difficulty: "Medium",
        },
        {
          id: `${quizId}-s2-q3`,
          question: `Analyze the tradeoff in "${bp.topic}" between immediate strong consistency and high availability under network partitions:`,
          options: [
            `Strong consistency requires synchronous coordination across replicas, sacrificing low-latency availability during splits`,
            `Strong consistency guarantees zero latency across intercontinental links`,
            `High availability cannot function with any form of database replication`,
            `There is never any tradeoff between consistency and availability in distributed systems`,
          ],
          correctIndex: 0,
          explanation: `Per the CAP/PACELC theorems, enforcing linearizability and strong consistency mandates cross-node agreement, introducing synchronization latency.`,
          difficulty: "Medium",
        },
        {
          id: `${quizId}-s2-q4`,
          question: `In the context of ${bp.topic}, what happens when an unchecked cyclic dependency arises between concurrent units of execution?`,
          options: [
            `The system automatically executes all units in reverse order`,
            `A deadlock state is reached where all involved execution contexts remain blocked indefinitely`,
            `CPU clock frequency automatically multiplies to resolve the cycle`,
            `The compiler resolves the cycle at runtime without any intervention`,
          ],
          correctIndex: 1,
          explanation: `Circular wait is one of the four Coffman conditions that causes deadlock, requiring preemption or lock ordering to resolve.`,
          difficulty: "Medium",
        },
        {
          id: `${quizId}-s2-q5`,
          question: `Which diagnostic technique is most effective for profiling performance bottlenecks and memory leaks in ${bp.sub}?`,
          options: [
            `Examining flame graphs, CPU instruction cycle profiling, and heap allocation snapshots`,
            `Increasing system RAM without analyzing allocation patterns`,
            `Recompiling the entire code in debug mode and deploying to production`,
            `Ignoring stack traces and restarting the daemon continuously`,
          ],
          correctIndex: 0,
          explanation: `Flame graphs and flame charts combined with heap dumps isolate hot paths and memory retention cycles precisely.`,
          difficulty: "Medium",
        },
      ];

      // Section 3: 5 Hard Questions
      const section3Hard: CsQuizMcqQuestion[] = [
        {
          id: `${quizId}-s3-q1`,
          question: `Deep Internals: In low-latency architectures for ${bp.topic}, what is the impact of CPU cache line false sharing and how is it eliminated?`,
          options: [
            `Multiple cores invalidate each other's L1/L2 cache lines for unrelated variables on the same 64-byte line; eliminated by memory padding and alignment`,
            `False sharing only happens in single-threaded Python scripts`,
            `It is cured by disabling L3 CPU cache in the BIOS`,
            `It has zero measurable effect on multicore throughput`,
          ],
          correctIndex: 0,
          explanation: `When independent variables reside in the same 64-byte cache line accessed by different CPU cores, MESI invalidation storms occur. Aligning variables (e.g. alignas(64)) prevents this.`,
          difficulty: "Hard",
        },
        {
          id: `${quizId}-s3-q2`,
          question: `Hardware-Software Boundary: How does ${bp.sub} maintain memory order consistency across non-sequentially consistent modern architectures (e.g. ARM vs x86)?`,
          options: [
            `x86 has total store order (TSO) while ARM has weak ordering; memory fences (MFENCE / DMB) and atomic acquire-release semantics enforce cross-core visibility`,
            `All hardware architectures guarantee strict sequential consistency automatically`,
            `Compilers ignore memory ordering rules completely`,
            `Thread synchronization is purely simulated in user-space without kernel primitives`,
          ],
          correctIndex: 0,
          explanation: `ARM architectures utilize weakly ordered memory models requiring explicit acquire/release memory barriers to prevent CPU instruction reordering.`,
          difficulty: "Hard",
        },
        {
          id: `${quizId}-s3-q3`,
          question: `Under heavy Byzantine or network fault conditions in ${bp.topic}, why does a distributed quorum require strictly 2f + 1 nodes to tolerate f crash faults and 3f + 1 for Byzantine faults?`,
          options: [
            `In crash faults, a non-faulty majority of (N - f) is needed to overlap with any prior quorum; in Byzantine faults, malicious nodes can send conflicting messages requiring (N - f) > 2f`,
            `Because prime numbers are required for hash partitioning`,
            `Fault tolerance only works when N is an even number`,
            `Byzantine nodes are automatically converted into trusted nodes by the network router`,
          ],
          correctIndex: 0,
          explanation: `In standard crash-fault consensus (Raft/Paxos), N=2f+1 ensures any two majorities intersect in at least 1 correct node. For Byzantine Fault Tolerance (PBFT), N=3f+1 is mathematically required.`,
          difficulty: "Hard",
        },
        {
          id: `${quizId}-s3-q4`,
          question: `What critical vulnerability occurs if ${bp.topic} utilizes non-cryptographically secure random generators or predictable sequential state counters?`,
          options: [
            `Adversaries can compute future seed outputs, spoof session tokens, and bypass cryptographic nonces or TLS handshake security`,
            `The program simply runs faster with higher throughput`,
            `Memory consumption is doubled on every function call`,
            `It triggers an unrecoverable kernel panic on boot`,
          ],
          correctIndex: 0,
          explanation: `Predictable pseudo-random numbers (e.g. standard LCG / rand()) allow attackers to predict tokens, cryptographic keys, and TCP sequence numbers (ISN spoofing).`,
          difficulty: "Hard",
        },
        {
          id: `${quizId}-s3-q5`,
          question: `When implementing lock-free data structures in ${bp.sub}, how does the ABA problem manifest and what is the standard algorithmic remedy?`,
          options: [
            `A pointer changes from A to B and back to A between compare-and-swap (CAS) checks; solved via tagged pointers (pointer + version counter) or double-word CAS (DCAS)`,
            `ABA is a compiler optimization bug that occurs only in C++98`,
            `It is solved by making all pointer variables global and static`,
            `It can only be resolved by converting the entire algorithm to use standard OS kernel mutexes`,
          ],
          correctIndex: 0,
          explanation: `The ABA problem occurs when a memory location is read as A, updated to B, and updated back to A, causing a naive CAS to succeed erroneously. Tagging pointers with version numbers prevents this.`,
          difficulty: "Hard",
        },
      ];

      quizzes.push({
        id: quizId,
        quizNumber: globalQuizNumber,
        subjectId: subject.id,
        subjectName: subject.subject,
        title: bp.topic,
        subtopic: bp.sub,
        targetLevel:
          globalQuizNumber % 3 === 0
            ? "Tier 1 Specialist"
            : globalQuizNumber % 2 === 0
            ? "Advanced Mastery"
            : "Core Foundation",
        durationMinutes: 25,
        passingScore: 70,
        section1Easy,
        section2Medium,
        section3Hard,
      });

      globalQuizNumber++;
    });
  }

  return quizzes;
}

export const ALL_CS_QUIZZES_200: CsQuizItem[] = generateAll200CsQuizzes();
