/**
 * Official Curriculum Template for Super Dream 20+ LPA Track
 * Pure template with zero mock progress (all counters start at 0, status at "Not Started", no mock signatures).
 */
function createDefaultChecklist(studentName = "Student Candidate", regNo = "", dept = "", targetRole = "") {
  return {
    profile: {
      id: "std-primary",
      name: studentName,
      registerNumber: regNo || "",
      department: dept || "",
      batch: "",
      facultyMentor: "",
      currentSemester: "",
      targetRole: targetRole || "",
      targetCompanyTier: "",
    },
    section1Programming: [
      { id: "p-1", skill: "C Programming", target: "Advanced", status: "Not Started", facultyRemarks: "", problemsSolved: 0, hoursSpent: 0, subtopicsMastered: [], visitedLinks: [], bestQuizScore: 0, quizPassed: false, quizIntegrityScore: 0 },
      { id: "p-2", skill: "C++", target: "Advanced", status: "Not Started", facultyRemarks: "", problemsSolved: 0, hoursSpent: 0, subtopicsMastered: [], visitedLinks: [], bestQuizScore: 0, quizPassed: false, quizIntegrityScore: 0 },
      { id: "p-3", skill: "Python", target: "Advanced", status: "Not Started", facultyRemarks: "", problemsSolved: 0, hoursSpent: 0, subtopicsMastered: [], visitedLinks: [], bestQuizScore: 0, quizPassed: false, quizIntegrityScore: 0 },
      { id: "p-4", skill: "Java", target: "Advanced", status: "Not Started", facultyRemarks: "", problemsSolved: 0, hoursSpent: 0, subtopicsMastered: [], visitedLinks: [], bestQuizScore: 0, quizPassed: false, quizIntegrityScore: 0 },
      { id: "p-5", skill: "JavaScript / TypeScript", target: "Advanced", status: "Not Started", facultyRemarks: "", problemsSolved: 0, hoursSpent: 0, subtopicsMastered: [], visitedLinks: [], bestQuizScore: 0, quizPassed: false, quizIntegrityScore: 0 },
      { id: "p-6", skill: "Go (Golang)", target: "Intermediate to Advanced", status: "Not Started", facultyRemarks: "", problemsSolved: 0, hoursSpent: 0, subtopicsMastered: [], visitedLinks: [], bestQuizScore: 0, quizPassed: false, quizIntegrityScore: 0 },
      { id: "p-7", skill: "SQL & Query Optimization", target: "Advanced", status: "Not Started", facultyRemarks: "", problemsSolved: 0, hoursSpent: 0, subtopicsMastered: [], visitedLinks: [], bestQuizScore: 0, quizPassed: false, quizIntegrityScore: 0 },
      { id: "p-8", skill: "Object-Oriented Programming (OOP)", target: "Excellent", status: "Not Started", facultyRemarks: "", problemsSolved: 0, hoursSpent: 0, subtopicsMastered: [], visitedLinks: [], bestQuizScore: 0, quizPassed: false, quizIntegrityScore: 0 },
      { id: "p-9", skill: "Design Patterns & Architecture", target: "Working Knowledge", status: "Not Started", facultyRemarks: "", problemsSolved: 0, hoursSpent: 0, subtopicsMastered: [], visitedLinks: [], bestQuizScore: 0, quizPassed: false, quizIntegrityScore: 0 },
    ],
    section2CsFundamentals: [
      { id: "cs-1", subject: "Data Structures", rating: 0, completed: false, remarks: "" },
      { id: "cs-2", subject: "Algorithms", rating: 0, completed: false, remarks: "" },
      { id: "cs-3", subject: "Operating Systems", rating: 0, completed: false, remarks: "" },
      { id: "cs-4", subject: "Computer Networks", rating: 0, completed: false, remarks: "" },
      { id: "cs-5", subject: "DBMS & Transactions", rating: 0, completed: false, remarks: "" },
      { id: "cs-6", subject: "Distributed Systems", rating: 0, completed: false, remarks: "" },
      { id: "cs-7", subject: "System Design (HLD & LLD)", rating: 0, completed: false, remarks: "" },
      { id: "cs-8", subject: "Compiler Design", rating: 0, completed: false, remarks: "" },
      { id: "cs-9", subject: "Computer Architecture", rating: 0, completed: false, remarks: "" },
      { id: "cs-10", subject: "Software Engineering & CI/CD", rating: 0, completed: false, remarks: "" },
    ],
    section3CodingDsa: [
      { id: "dsa-1", activity: "LeetCode Problems Solved", target: 450, current: 0 },
      { id: "dsa-2", activity: "HackerRank Problems Solved", target: 300, current: 0 },
      { id: "dsa-3", activity: "Codeforces Contests Attended", target: 30, current: 0 },
      { id: "dsa-4", activity: "Total Coding Contests Attended", target: 50, current: 0 },
      { id: "dsa-5", activity: "Dynamic Programming Solved", target: 100, current: 0 },
      { id: "dsa-6", activity: "Graph Theory & Flow Problems", target: 80, current: 0 },
      { id: "dsa-7", activity: "Tree & Binary Search Problems", target: 80, current: 0 },
      { id: "dsa-8", activity: "Hard / FAANG-Tier Problems", target: 75, current: 0 },
      { id: "dsa-9", activity: "Weekly Coding Hours", target: 15, current: 0 },
      { id: "dsa-10", activity: "LeetCode Contest Rating", target: 1850, current: 0 },
    ],
    section4SoftwareDev: [
      {
        id: "dev-1",
        projectNumber: 1,
        activity: "Distributed Systems / Microservices Project",
        category: "Systems & Distributed Systems",
        description: "Production-ready backend with gRPC/REST, distributed transactions, and database clustering.",
        techStack: ["Go / Node.js", "Docker", "PostgreSQL", "Redis"],
        target: 1,
        current: 0,
        githubUrl: "",
        repoUrl: "",
        liveUrl: "",
        verified: false,
        mentorFeedback: "",
      },
      {
        id: "dev-2",
        projectNumber: 2,
        activity: "High-Throughput Concurrency / Performance Engine",
        category: "Low-Latency Engineering",
        description: "Thread-safe data structures, cache optimization, and zero-allocation pipelines.",
        techStack: ["C++ / Rust / Java", "Google Benchmark", "POSIX Threads"],
        target: 1,
        current: 0,
        githubUrl: "",
        repoUrl: "",
        liveUrl: "",
        verified: false,
        mentorFeedback: "",
      },
      {
        id: "dev-3",
        projectNumber: 3,
        activity: "Distributed Rate Limiter & API Gateway",
        category: "Backend & Microservices",
        description: "Token bucket / sliding window rate limiter with Redis cluster backend.",
        techStack: ["Node.js / Go", "Redis", "Docker", "Express / Gin"],
        target: 1,
        current: 0,
        githubUrl: "",
        repoUrl: "",
        liveUrl: "",
        verified: false,
        mentorFeedback: "",
      },
      {
        id: "dev-4",
        projectNumber: 4,
        activity: "Full-Stack Enterprise Cloud Application",
        category: "Full Stack & Microservices",
        description: "Full-stack application with authentication, real-time websockets, and responsive UI.",
        techStack: ["React", "TypeScript", "Node.js", "MongoDB / PostgreSQL", "Tailwind CSS"],
        target: 1,
        current: 0,
        githubUrl: "",
        repoUrl: "",
        liveUrl: "",
        verified: false,
        mentorFeedback: "",
      },
    ],
    section5AiDataScience: [
      { id: "ai-1", activity: "High Accuracy Machine Learning Pipeline", target: 10, current: 0, framework: "Scikit-Learn / XGBoost", verified: false },
      { id: "ai-2", activity: "Deep Learning & Neural Network Architecture", target: 8, current: 0, framework: "PyTorch / TensorFlow", verified: false },
      { id: "ai-3", activity: "Computer Vision Model & Inference Pipeline", target: 5, current: 0, framework: "OpenCV / YOLO", verified: false },
      { id: "ai-4", activity: "Natural Language Processing (NLP) & Embeddings", target: 5, current: 0, framework: "Transformers / SpaCy", verified: false },
      { id: "ai-5", activity: "Generative AI RAG Application with Vector DB", target: 5, current: 0, framework: "LangChain / LlamaIndex / Qdrant", verified: false },
      { id: "ai-6", activity: "Autonomous AI Agent Workflow", target: 4, current: 0, framework: "CrewAI / AutoGen", verified: false },
    ],
    section6CloudDevOps: [
      { id: "c-1", activity: "AWS Core Cloud Services Architecture (ECS, S3, RDS, Lambda)", target: 20, current: 0, cloudProvider: "AWS", verified: false },
      { id: "c-2", activity: "Azure Cloud Deployments & Compute Services", target: 15, current: 0, cloudProvider: "Azure", verified: false },
      { id: "c-3", activity: "Google Cloud Platform Infrastructure & BigQuery", target: 10, current: 0, cloudProvider: "GCP", verified: false },
      { id: "c-4", activity: "Terraform Infrastructure-as-Code Modules", target: 10, current: 0, verified: false },
      { id: "c-5", activity: "Docker Multi-Stage Optimized Containers", target: 20, current: 0, verified: false },
      { id: "c-6", activity: "Kubernetes Microservices Ingress & HPA Deployments", target: 15, current: 0, verified: false },
    ],
    section7GithubPortfolio: [
      { id: "gh-1", activity: "Public GitHub Repositories", target: 25, targetDisplay: "25", targetValue: 25, current: 0, unit: "Repositories", verified: false },
      { id: "gh-2", activity: "Total Git Commits", target: "2500+", targetDisplay: "2500+", targetValue: 2500, current: 0, unit: "Commits", verified: false },
      { id: "gh-3", activity: "Pull Requests Merged", target: 25, targetDisplay: "25", targetValue: 25, current: 0, unit: "Pull Requests", verified: false },
      { id: "gh-4", activity: "Open Source Upstream Contributions", target: 10, targetDisplay: "10", targetValue: 10, current: 0, unit: "Contributions", verified: false },
      { id: "gh-5", activity: "GitHub Stars Earned", target: 50, targetDisplay: "50", targetValue: 50, current: 0, unit: "Stars", verified: false },
      { id: "gh-6", activity: "Technical Architecture Specifications & READMEs", target: 40, targetDisplay: "40", targetValue: 40, current: 0, unit: "Articles / Specs", verified: false },
      { id: "gh-7", activity: "Live Deployed Portfolio Website", target: "Completed", targetDisplay: "Completed", targetValue: 1, current: 0, isCompleted: false, liveUrl: "", verified: false },
    ],
    section8Certifications: [
      { id: "cert-1", certification: "AWS Certified Solutions Architect – Associate", issuer: "Amazon Web Services", status: "Not Started", credentialId: "", certificatePdfName: "", verified: false },
      { id: "cert-2", certification: "Certified Kubernetes Administrator (CKA)", issuer: "Linux Foundation / CNCF", status: "Not Started", credentialId: "", certificatePdfName: "", verified: false },
      { id: "cert-3", certification: "Google Cloud Associate Cloud Engineer", issuer: "Google Cloud", status: "Not Started", credentialId: "", certificatePdfName: "", verified: false },
      { id: "cert-4", certification: "DeepLearning.AI Generative AI with LLMs", issuer: "DeepLearning.AI & AWS", status: "Not Started", credentialId: "", certificatePdfName: "", verified: false },
      { id: "cert-5", certification: "Oracle Certified Professional: Java SE 17", issuer: "Oracle University", status: "Not Started", credentialId: "", certificatePdfName: "", verified: false },
    ],
    section9InterviewPrep: [
      { id: "iv-1", activity: "Mock Technical Coding Rounds", target: 30, current: 0 },
      { id: "iv-2", activity: "System Design Bar-Raiser Interviews", target: 20, current: 0 },
      { id: "iv-3", activity: "Behavioral & Leadership Rounds", target: 15, current: 0 },
      { id: "iv-4", activity: "Aptitude & Logical Reasoning Tests", target: 35, current: 0 },
      { id: "iv-5", activity: "AI Real-Time Mock Interview Sessions", target: 10, current: 0 },
    ],
    section10Evaluation: {
      strengths: "",
      areasForImprovement: "",
      actionPlanNextSemester: "",
      recommendedLearningPaths: [],
      studentSignature: "",
      studentSignedDate: "",
      facultyMentorSignature: "",
      facultyMentorSignedDate: "",
      hodSignature: "",
      hodSignedDate: "",
      reviewDate: "",
    },
  };
}

module.exports = { createDefaultChecklist };
